#!/bin/bash

MANIFEST=$1
if [[ -z ${MANIFEST} ]]; then
	echo >&2 "USAGE: $0 manifest.yml"
	exit 1
fi

UUID=$(bosh status --uuid)
mkdir -p local
cat $MANIFEST | sed -e "s/^director_uuid:.*/director_uuid: ${UUID}/" > local/$MANIFEST
sha1sum local/$MANIFEST
bosh -d local/$MANIFEST -n deploy
