#!/bin/bash

MANIFEST=$1
if [[ -z ${MANIFEST} ]]; then
	echo >&2 "USAGE: $0 manifest.yml"
	exit 1
fi

UUID=$(bosh status --uuid)
cat $MANIFEST | sed -e "s/^director_uuid:.*/director_uuid: ${UUID}/" > current.yml
sha1sum current.yml
bosh -d current.yml -n deploy
